// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sms.proto

package sms_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	NameService          string   `protobuf:"bytes,1,opt,name=name_service,json=nameService,proto3" json:"name_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNameService() string {
	if m != nil {
		return m.NameService
	}
	return ""
}

type SmsSendRequest struct {
	NameService          string   `protobuf:"bytes,1,opt,name=name_service,json=nameService,proto3" json:"name_service,omitempty"`
	Phone                []string `protobuf:"bytes,2,rep,name=phone,proto3" json:"phone,omitempty"`
	Text                 []string `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsSendRequest) Reset()         { *m = SmsSendRequest{} }
func (m *SmsSendRequest) String() string { return proto.CompactTextString(m) }
func (*SmsSendRequest) ProtoMessage()    {}
func (*SmsSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{1}
}

func (m *SmsSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsSendRequest.Unmarshal(m, b)
}
func (m *SmsSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsSendRequest.Marshal(b, m, deterministic)
}
func (m *SmsSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsSendRequest.Merge(m, src)
}
func (m *SmsSendRequest) XXX_Size() int {
	return xxx_messageInfo_SmsSendRequest.Size(m)
}
func (m *SmsSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsSendRequest proto.InternalMessageInfo

func (m *SmsSendRequest) GetNameService() string {
	if m != nil {
		return m.NameService
	}
	return ""
}

func (m *SmsSendRequest) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *SmsSendRequest) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

type SmsStatusRequest struct {
	NameService          string   `protobuf:"bytes,1,opt,name=name_service,json=nameService,proto3" json:"name_service,omitempty"`
	Phone                []string `protobuf:"bytes,2,rep,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsStatusRequest) Reset()         { *m = SmsStatusRequest{} }
func (m *SmsStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SmsStatusRequest) ProtoMessage()    {}
func (*SmsStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{2}
}

func (m *SmsStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsStatusRequest.Unmarshal(m, b)
}
func (m *SmsStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsStatusRequest.Marshal(b, m, deterministic)
}
func (m *SmsStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsStatusRequest.Merge(m, src)
}
func (m *SmsStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SmsStatusRequest.Size(m)
}
func (m *SmsStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsStatusRequest proto.InternalMessageInfo

func (m *SmsStatusRequest) GetNameService() string {
	if m != nil {
		return m.NameService
	}
	return ""
}

func (m *SmsStatusRequest) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

type SmsMagfaStatus struct {
	Status               []string `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsMagfaStatus) Reset()         { *m = SmsMagfaStatus{} }
func (m *SmsMagfaStatus) String() string { return proto.CompactTextString(m) }
func (*SmsMagfaStatus) ProtoMessage()    {}
func (*SmsMagfaStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{3}
}

func (m *SmsMagfaStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsMagfaStatus.Unmarshal(m, b)
}
func (m *SmsMagfaStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsMagfaStatus.Marshal(b, m, deterministic)
}
func (m *SmsMagfaStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsMagfaStatus.Merge(m, src)
}
func (m *SmsMagfaStatus) XXX_Size() int {
	return xxx_messageInfo_SmsMagfaStatus.Size(m)
}
func (m *SmsMagfaStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsMagfaStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmsMagfaStatus proto.InternalMessageInfo

func (m *SmsMagfaStatus) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

type SmsMagfaStatusServiceResponse struct {
	Result               *SmsMagfaStatus `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SmsMagfaStatusServiceResponse) Reset()         { *m = SmsMagfaStatusServiceResponse{} }
func (m *SmsMagfaStatusServiceResponse) String() string { return proto.CompactTextString(m) }
func (*SmsMagfaStatusServiceResponse) ProtoMessage()    {}
func (*SmsMagfaStatusServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{4}
}

func (m *SmsMagfaStatusServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsMagfaStatusServiceResponse.Unmarshal(m, b)
}
func (m *SmsMagfaStatusServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsMagfaStatusServiceResponse.Marshal(b, m, deterministic)
}
func (m *SmsMagfaStatusServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsMagfaStatusServiceResponse.Merge(m, src)
}
func (m *SmsMagfaStatusServiceResponse) XXX_Size() int {
	return xxx_messageInfo_SmsMagfaStatusServiceResponse.Size(m)
}
func (m *SmsMagfaStatusServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsMagfaStatusServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsMagfaStatusServiceResponse proto.InternalMessageInfo

func (m *SmsMagfaStatusServiceResponse) GetResult() *SmsMagfaStatus {
	if m != nil {
		return m.Result
	}
	return nil
}

type SmsMagfa struct {
	SmsId                []string `protobuf:"bytes,1,rep,name=sms_id,json=smsId,proto3" json:"sms_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsMagfa) Reset()         { *m = SmsMagfa{} }
func (m *SmsMagfa) String() string { return proto.CompactTextString(m) }
func (*SmsMagfa) ProtoMessage()    {}
func (*SmsMagfa) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{5}
}

func (m *SmsMagfa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsMagfa.Unmarshal(m, b)
}
func (m *SmsMagfa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsMagfa.Marshal(b, m, deterministic)
}
func (m *SmsMagfa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsMagfa.Merge(m, src)
}
func (m *SmsMagfa) XXX_Size() int {
	return xxx_messageInfo_SmsMagfa.Size(m)
}
func (m *SmsMagfa) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsMagfa.DiscardUnknown(m)
}

var xxx_messageInfo_SmsMagfa proto.InternalMessageInfo

func (m *SmsMagfa) GetSmsId() []string {
	if m != nil {
		return m.SmsId
	}
	return nil
}

type SmsMagfaServiceResponse struct {
	Result               *SmsMagfa `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	StatusCode           int32     `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SmsMagfaServiceResponse) Reset()         { *m = SmsMagfaServiceResponse{} }
func (m *SmsMagfaServiceResponse) String() string { return proto.CompactTextString(m) }
func (*SmsMagfaServiceResponse) ProtoMessage()    {}
func (*SmsMagfaServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{6}
}

func (m *SmsMagfaServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsMagfaServiceResponse.Unmarshal(m, b)
}
func (m *SmsMagfaServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsMagfaServiceResponse.Marshal(b, m, deterministic)
}
func (m *SmsMagfaServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsMagfaServiceResponse.Merge(m, src)
}
func (m *SmsMagfaServiceResponse) XXX_Size() int {
	return xxx_messageInfo_SmsMagfaServiceResponse.Size(m)
}
func (m *SmsMagfaServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsMagfaServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsMagfaServiceResponse proto.InternalMessageInfo

func (m *SmsMagfaServiceResponse) GetResult() *SmsMagfa {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *SmsMagfaServiceResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type SmsDb struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsDb) Reset()         { *m = SmsDb{} }
func (m *SmsDb) String() string { return proto.CompactTextString(m) }
func (*SmsDb) ProtoMessage()    {}
func (*SmsDb) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{7}
}

func (m *SmsDb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsDb.Unmarshal(m, b)
}
func (m *SmsDb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsDb.Marshal(b, m, deterministic)
}
func (m *SmsDb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsDb.Merge(m, src)
}
func (m *SmsDb) XXX_Size() int {
	return xxx_messageInfo_SmsDb.Size(m)
}
func (m *SmsDb) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsDb.DiscardUnknown(m)
}

var xxx_messageInfo_SmsDb proto.InternalMessageInfo

func (m *SmsDb) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmsDb) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SmsDb) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type SmsDbServiceResponse struct {
	Result               []*SmsDb `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsDbServiceResponse) Reset()         { *m = SmsDbServiceResponse{} }
func (m *SmsDbServiceResponse) String() string { return proto.CompactTextString(m) }
func (*SmsDbServiceResponse) ProtoMessage()    {}
func (*SmsDbServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6052ccaf8f0b6c51, []int{8}
}

func (m *SmsDbServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsDbServiceResponse.Unmarshal(m, b)
}
func (m *SmsDbServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsDbServiceResponse.Marshal(b, m, deterministic)
}
func (m *SmsDbServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsDbServiceResponse.Merge(m, src)
}
func (m *SmsDbServiceResponse) XXX_Size() int {
	return xxx_messageInfo_SmsDbServiceResponse.Size(m)
}
func (m *SmsDbServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsDbServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsDbServiceResponse proto.InternalMessageInfo

func (m *SmsDbServiceResponse) GetResult() []*SmsDb {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "sms_service.Request")
	proto.RegisterType((*SmsSendRequest)(nil), "sms_service.SmsSendRequest")
	proto.RegisterType((*SmsStatusRequest)(nil), "sms_service.SmsStatusRequest")
	proto.RegisterType((*SmsMagfaStatus)(nil), "sms_service.SmsMagfaStatus")
	proto.RegisterType((*SmsMagfaStatusServiceResponse)(nil), "sms_service.SmsMagfaStatusServiceResponse")
	proto.RegisterType((*SmsMagfa)(nil), "sms_service.SmsMagfa")
	proto.RegisterType((*SmsMagfaServiceResponse)(nil), "sms_service.SmsMagfaServiceResponse")
	proto.RegisterType((*SmsDb)(nil), "sms_service.SmsDb")
	proto.RegisterType((*SmsDbServiceResponse)(nil), "sms_service.SmsDbServiceResponse")
}

func init() { proto.RegisterFile("proto/sms.proto", fileDescriptor_6052ccaf8f0b6c51) }

var fileDescriptor_6052ccaf8f0b6c51 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xef, 0x4a, 0x83, 0x50,
	0x14, 0xc7, 0x99, 0xd6, 0x8e, 0xa3, 0xe2, 0xb2, 0x95, 0x2c, 0x46, 0xdb, 0xa5, 0x0f, 0x32, 0x6a,
	0xc1, 0xf6, 0x06, 0x35, 0x88, 0x18, 0x11, 0x68, 0x5f, 0xc7, 0xd0, 0x79, 0x2b, 0xa1, 0xab, 0xcb,
	0xa3, 0xd1, 0x0b, 0xf4, 0xde, 0x71, 0xaf, 0x1a, 0x7a, 0x37, 0x22, 0xe8, 0xdb, 0x39, 0xe7, 0x9e,
	0xdf, 0x9f, 0xfd, 0x76, 0x84, 0xa3, 0x4d, 0x9a, 0x64, 0xc9, 0x35, 0x72, 0x9c, 0xc8, 0x8a, 0x58,
	0xc8, 0x71, 0x85, 0x2c, 0xfd, 0x88, 0xd6, 0x8c, 0x5e, 0xc2, 0xbe, 0xcb, 0xde, 0x73, 0x86, 0x19,
	0x19, 0x41, 0x27, 0xf6, 0x39, 0xab, 0x9e, 0x6c, 0x6d, 0xa8, 0x39, 0x6d, 0xd7, 0x12, 0x33, 0xaf,
	0xdc, 0x5e, 0xc2, 0xa1, 0xc7, 0xd1, 0x63, 0x71, 0xf8, 0x77, 0x10, 0xe9, 0x82, 0xb1, 0x79, 0x4d,
	0x62, 0x66, 0xb7, 0x86, 0xba, 0xd3, 0x76, 0x8b, 0x86, 0x10, 0xd8, 0xcb, 0xd8, 0x67, 0x66, 0xeb,
	0x72, 0x28, 0x6b, 0xba, 0x80, 0x63, 0x41, 0x9f, 0xf9, 0x59, 0x8e, 0xff, 0x15, 0xa0, 0x8e, 0xf4,
	0xfa, 0xe0, 0xbf, 0x3c, 0xfb, 0x05, 0x23, 0x39, 0x01, 0x13, 0x65, 0x65, 0x6b, 0x72, 0xb1, 0xec,
	0xe8, 0x13, 0x0c, 0x9a, 0x9b, 0x25, 0xb1, 0xcb, 0x70, 0x93, 0xc4, 0xc8, 0xc8, 0x0c, 0xcc, 0x94,
	0x61, 0xfe, 0x96, 0x49, 0x75, 0x6b, 0x7a, 0x36, 0xa9, 0x45, 0x38, 0x69, 0x62, 0xdd, 0x72, 0x95,
	0x8e, 0xe0, 0xa0, 0x7a, 0x21, 0x3d, 0x30, 0x05, 0x22, 0x0a, 0x4b, 0x65, 0x03, 0x39, 0xde, 0x87,
	0x34, 0x82, 0xd3, 0x1f, 0xb0, 0x22, 0x79, 0xa5, 0x48, 0xf6, 0x76, 0x4a, 0x56, 0x62, 0xe4, 0x1c,
	0xac, 0xe2, 0xc7, 0xac, 0xd6, 0x49, 0x28, 0x82, 0xd0, 0x1c, 0xc3, 0x85, 0x62, 0x74, 0x9b, 0x84,
	0x8c, 0x2e, 0xc0, 0xf0, 0x38, 0xce, 0x03, 0x91, 0xbb, 0xc8, 0xae, 0xcc, 0x51, 0xd6, 0x22, 0x98,
	0x30, 0xe1, 0x7e, 0x14, 0x4b, 0x60, 0xdb, 0x2d, 0x3b, 0x31, 0x8f, 0x73, 0x1e, 0xb0, 0xd4, 0xd6,
	0x8b, 0x79, 0xd1, 0xd1, 0x1b, 0xe8, 0x4a, 0x32, 0xd5, 0xf4, 0xb8, 0x66, 0x5a, 0x77, 0xac, 0x29,
	0x51, 0x4d, 0xcf, 0x83, 0xca, 0xf1, 0xf4, 0xab, 0x05, 0x20, 0x6f, 0xa9, 0xf8, 0x0f, 0x1f, 0x1b,
	0xdd, 0x56, 0xc0, 0xb5, 0x93, 0xeb, 0x5f, 0xec, 0x4e, 0x5f, 0xf1, 0x72, 0x07, 0x9d, 0xba, 0x47,
	0xd2, 0x6d, 0xa0, 0x2a, 0xae, 0xd1, 0xb6, 0x43, 0x95, 0x68, 0x59, 0x3b, 0xca, 0x8a, 0x6c, 0xb0,
	0xe5, 0xaf, 0x7e, 0xb3, 0xfd, 0xf1, 0x2f, 0xf7, 0xa1, 0xd0, 0x07, 0xa6, 0xfc, 0x28, 0x67, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0x1e, 0xdb, 0x8d, 0xa7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmsServiceClient is the client API for SmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsServiceClient interface {
	SmsService(ctx context.Context, in *SmsSendRequest, opts ...grpc.CallOption) (*SmsMagfaServiceResponse, error)
	SmsDbService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*SmsDbServiceResponse, error)
	SmsStatusService(ctx context.Context, in *SmsStatusRequest, opts ...grpc.CallOption) (*SmsMagfaStatusServiceResponse, error)
}

type smsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSmsServiceClient(cc *grpc.ClientConn) SmsServiceClient {
	return &smsServiceClient{cc}
}

func (c *smsServiceClient) SmsService(ctx context.Context, in *SmsSendRequest, opts ...grpc.CallOption) (*SmsMagfaServiceResponse, error) {
	out := new(SmsMagfaServiceResponse)
	err := c.cc.Invoke(ctx, "/sms_service.SmsService/SmsService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) SmsDbService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*SmsDbServiceResponse, error) {
	out := new(SmsDbServiceResponse)
	err := c.cc.Invoke(ctx, "/sms_service.SmsService/SmsDbService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) SmsStatusService(ctx context.Context, in *SmsStatusRequest, opts ...grpc.CallOption) (*SmsMagfaStatusServiceResponse, error) {
	out := new(SmsMagfaStatusServiceResponse)
	err := c.cc.Invoke(ctx, "/sms_service.SmsService/SmsStatusService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServiceServer is the server API for SmsService service.
type SmsServiceServer interface {
	SmsService(context.Context, *SmsSendRequest) (*SmsMagfaServiceResponse, error)
	SmsDbService(context.Context, *Request) (*SmsDbServiceResponse, error)
	SmsStatusService(context.Context, *SmsStatusRequest) (*SmsMagfaStatusServiceResponse, error)
}

// UnimplementedSmsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSmsServiceServer struct {
}

func (*UnimplementedSmsServiceServer) SmsService(ctx context.Context, req *SmsSendRequest) (*SmsMagfaServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SmsService not implemented")
}
func (*UnimplementedSmsServiceServer) SmsDbService(ctx context.Context, req *Request) (*SmsDbServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SmsDbService not implemented")
}
func (*UnimplementedSmsServiceServer) SmsStatusService(ctx context.Context, req *SmsStatusRequest) (*SmsMagfaStatusServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SmsStatusService not implemented")
}

func RegisterSmsServiceServer(s *grpc.Server, srv SmsServiceServer) {
	s.RegisterService(&_SmsService_serviceDesc, srv)
}

func _SmsService_SmsService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).SmsService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms_service.SmsService/SmsService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).SmsService(ctx, req.(*SmsSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_SmsDbService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).SmsDbService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms_service.SmsService/SmsDbService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).SmsDbService(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_SmsStatusService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).SmsStatusService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms_service.SmsService/SmsStatusService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).SmsStatusService(ctx, req.(*SmsStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sms_service.SmsService",
	HandlerType: (*SmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SmsService",
			Handler:    _SmsService_SmsService_Handler,
		},
		{
			MethodName: "SmsDbService",
			Handler:    _SmsService_SmsDbService_Handler,
		},
		{
			MethodName: "SmsStatusService",
			Handler:    _SmsService_SmsStatusService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sms.proto",
}
