// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/customer.proto

package genders

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenderListResponse struct {
	Genderitemresponse   []*GenderItemResponse `protobuf:"bytes,1,rep,name=genderitemresponse,proto3" json:"genderitemresponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GenderListResponse) Reset()         { *m = GenderListResponse{} }
func (m *GenderListResponse) String() string { return proto.CompactTextString(m) }
func (*GenderListResponse) ProtoMessage()    {}
func (*GenderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{0}
}

func (m *GenderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderListResponse.Unmarshal(m, b)
}
func (m *GenderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderListResponse.Marshal(b, m, deterministic)
}
func (m *GenderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderListResponse.Merge(m, src)
}
func (m *GenderListResponse) XXX_Size() int {
	return xxx_messageInfo_GenderListResponse.Size(m)
}
func (m *GenderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenderListResponse proto.InternalMessageInfo

func (m *GenderListResponse) GetGenderitemresponse() []*GenderItemResponse {
	if m != nil {
		return m.Genderitemresponse
	}
	return nil
}

type GenderItemResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenderItemResponse) Reset()         { *m = GenderItemResponse{} }
func (m *GenderItemResponse) String() string { return proto.CompactTextString(m) }
func (*GenderItemResponse) ProtoMessage()    {}
func (*GenderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{1}
}

func (m *GenderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderItemResponse.Unmarshal(m, b)
}
func (m *GenderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderItemResponse.Marshal(b, m, deterministic)
}
func (m *GenderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderItemResponse.Merge(m, src)
}
func (m *GenderItemResponse) XXX_Size() int {
	return xxx_messageInfo_GenderItemResponse.Size(m)
}
func (m *GenderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenderItemResponse proto.InternalMessageInfo

func (m *GenderItemResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GenderItemResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GenderItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenderItemRequest) Reset()         { *m = GenderItemRequest{} }
func (m *GenderItemRequest) String() string { return proto.CompactTextString(m) }
func (*GenderItemRequest) ProtoMessage()    {}
func (*GenderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{2}
}

func (m *GenderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderItemRequest.Unmarshal(m, b)
}
func (m *GenderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderItemRequest.Marshal(b, m, deterministic)
}
func (m *GenderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderItemRequest.Merge(m, src)
}
func (m *GenderItemRequest) XXX_Size() int {
	return xxx_messageInfo_GenderItemRequest.Size(m)
}
func (m *GenderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenderItemRequest proto.InternalMessageInfo

func (m *GenderItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateGenderItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGenderItemRequest) Reset()         { *m = CreateGenderItemRequest{} }
func (m *CreateGenderItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGenderItemRequest) ProtoMessage()    {}
func (*CreateGenderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{3}
}

func (m *CreateGenderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGenderItemRequest.Unmarshal(m, b)
}
func (m *CreateGenderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGenderItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateGenderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGenderItemRequest.Merge(m, src)
}
func (m *CreateGenderItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGenderItemRequest.Size(m)
}
func (m *CreateGenderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGenderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGenderItemRequest proto.InternalMessageInfo

func (m *CreateGenderItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteGenderItemResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGenderItemResponse) Reset()         { *m = DeleteGenderItemResponse{} }
func (m *DeleteGenderItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGenderItemResponse) ProtoMessage()    {}
func (*DeleteGenderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{4}
}

func (m *DeleteGenderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGenderItemResponse.Unmarshal(m, b)
}
func (m *DeleteGenderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGenderItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGenderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGenderItemResponse.Merge(m, src)
}
func (m *DeleteGenderItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGenderItemResponse.Size(m)
}
func (m *DeleteGenderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGenderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGenderItemResponse proto.InternalMessageInfo

func (m *DeleteGenderItemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GenderListResponse)(nil), "genders.GenderListResponse")
	proto.RegisterType((*GenderItemResponse)(nil), "genders.GenderItemResponse")
	proto.RegisterType((*GenderItemRequest)(nil), "genders.GenderItemRequest")
	proto.RegisterType((*CreateGenderItemRequest)(nil), "genders.CreateGenderItemRequest")
	proto.RegisterType((*DeleteGenderItemResponse)(nil), "genders.DeleteGenderItemResponse")
}

func init() { proto.RegisterFile("proto/customer.proto", fileDescriptor_d164c08f51b4bb12) }

var fileDescriptor_d164c08f51b4bb12 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x5d, 0x4f, 0xc2, 0x30,
	0x14, 0x86, 0xd9, 0x54, 0x08, 0xc7, 0x8f, 0xc4, 0x13, 0xa3, 0xcb, 0xb8, 0x99, 0xf5, 0x86, 0x1b,
	0x4b, 0x82, 0x5e, 0x78, 0x2b, 0x6a, 0x08, 0x6a, 0x62, 0xb2, 0x7f, 0x30, 0xdc, 0x71, 0x59, 0xb2,
	0x52, 0x5c, 0xcb, 0x05, 0x7f, 0xcd, 0x5f, 0x67, 0x6c, 0x57, 0x52, 0x11, 0x88, 0x77, 0xfd, 0x78,
	0x9f, 0xb7, 0x3d, 0x0f, 0x9c, 0xcd, 0x6b, 0xa9, 0xe5, 0xe0, 0x7d, 0xa1, 0xb4, 0x14, 0x54, 0x73,
	0xb3, 0xc5, 0x4e, 0x41, 0xb3, 0x9c, 0x6a, 0x15, 0xf7, 0x0a, 0x29, 0x8b, 0x8a, 0x06, 0xe6, 0x78,
	0xba, 0xf8, 0x18, 0x90, 0x98, 0xeb, 0xa5, 0x4d, 0xb1, 0x0c, 0x70, 0x6c, 0x72, 0xaf, 0xa5, 0xd2,
	0x29, 0xa9, 0xb9, 0x9c, 0x29, 0xc2, 0x17, 0x40, 0x4b, 0x97, 0x9a, 0x44, 0xdd, 0x9c, 0x46, 0x41,
	0xb2, 0xd7, 0x3f, 0x1c, 0xf6, 0x78, 0x53, 0xcc, 0x2d, 0x38, 0xd1, 0x24, 0x1c, 0x98, 0x6e, 0xc0,
	0xd8, 0x9d, 0x7b, 0xc2, 0x4f, 0xe2, 0x09, 0x84, 0x65, 0x1e, 0x05, 0x49, 0xd0, 0x3f, 0x48, 0xc3,
	0x32, 0x47, 0x84, 0xfd, 0x59, 0x26, 0x28, 0x0a, 0x93, 0xa0, 0xdf, 0x4d, 0xcd, 0x9a, 0x5d, 0xc1,
	0xa9, 0x4f, 0x7e, 0x2e, 0x48, 0xe9, 0x75, 0x90, 0x5d, 0xc3, 0xc5, 0x43, 0x4d, 0x99, 0xa6, 0xbf,
	0x51, 0xd7, 0x19, 0x78, 0x9d, 0xb7, 0x10, 0x3d, 0x52, 0x45, 0xbf, 0xe3, 0xcd, 0x9f, 0x22, 0xe8,
	0x08, 0x52, 0x2a, 0x2b, 0x1c, 0xe2, 0xb6, 0xc3, 0xaf, 0x10, 0xda, 0x16, 0xc0, 0x11, 0x74, 0xed,
	0xea, 0xbe, 0xaa, 0xf0, 0x9c, 0x5b, 0xb9, 0xdc, 0xc9, 0xe5, 0x4f, 0x3f, 0x72, 0xe3, 0x75, 0x49,
	0xbe, 0x5d, 0xd6, 0xc2, 0x67, 0x38, 0x1e, 0x93, 0xb6, 0x57, 0xa3, 0xe5, 0x24, 0xc7, 0x78, 0xa3,
	0x54, 0x33, 0x45, 0xbc, 0x4b, 0x38, 0x6b, 0xe1, 0x1b, 0x1c, 0xf9, 0xf3, 0x63, 0xb2, 0x8a, 0x6f,
	0xd1, 0xf2, 0x8f, 0x42, 0xdf, 0xd0, 0xce, 0xbf, 0x5d, 0xae, 0xee, 0xb6, 0x49, 0x65, 0xad, 0x69,
	0xdb, 0xc8, 0xb9, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xdc, 0xa8, 0x09, 0xa8, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GenderClient is the client API for Gender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenderClient interface {
	GenderAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenderListResponse, error)
	GetGenderById(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error)
	CreateGender(ctx context.Context, in *CreateGenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error)
	DeleteGender(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*DeleteGenderItemResponse, error)
}

type genderClient struct {
	cc *grpc.ClientConn
}

func NewGenderClient(cc *grpc.ClientConn) GenderClient {
	return &genderClient{cc}
}

func (c *genderClient) GenderAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenderListResponse, error) {
	out := new(GenderListResponse)
	err := c.cc.Invoke(ctx, "/genders.Gender/GenderAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genderClient) GetGenderById(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error) {
	out := new(GenderItemResponse)
	err := c.cc.Invoke(ctx, "/genders.Gender/GetGenderById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genderClient) CreateGender(ctx context.Context, in *CreateGenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error) {
	out := new(GenderItemResponse)
	err := c.cc.Invoke(ctx, "/genders.Gender/CreateGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genderClient) DeleteGender(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*DeleteGenderItemResponse, error) {
	out := new(DeleteGenderItemResponse)
	err := c.cc.Invoke(ctx, "/genders.Gender/DeleteGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenderServer is the server API for Gender service.
type GenderServer interface {
	GenderAll(context.Context, *empty.Empty) (*GenderListResponse, error)
	GetGenderById(context.Context, *GenderItemRequest) (*GenderItemResponse, error)
	CreateGender(context.Context, *CreateGenderItemRequest) (*GenderItemResponse, error)
	DeleteGender(context.Context, *GenderItemRequest) (*DeleteGenderItemResponse, error)
}

// UnimplementedGenderServer can be embedded to have forward compatible implementations.
type UnimplementedGenderServer struct {
}

func (*UnimplementedGenderServer) GenderAll(ctx context.Context, req *empty.Empty) (*GenderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenderAll not implemented")
}
func (*UnimplementedGenderServer) GetGenderById(ctx context.Context, req *GenderItemRequest) (*GenderItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenderById not implemented")
}
func (*UnimplementedGenderServer) CreateGender(ctx context.Context, req *CreateGenderItemRequest) (*GenderItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGender not implemented")
}
func (*UnimplementedGenderServer) DeleteGender(ctx context.Context, req *GenderItemRequest) (*DeleteGenderItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGender not implemented")
}

func RegisterGenderServer(s *grpc.Server, srv GenderServer) {
	s.RegisterService(&_Gender_serviceDesc, srv)
}

func _Gender_GenderAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServer).GenderAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genders.Gender/GenderAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServer).GenderAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gender_GetGenderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServer).GetGenderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genders.Gender/GetGenderById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServer).GetGenderById(ctx, req.(*GenderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gender_CreateGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGenderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServer).CreateGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genders.Gender/CreateGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServer).CreateGender(ctx, req.(*CreateGenderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gender_DeleteGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServer).DeleteGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genders.Gender/DeleteGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServer).DeleteGender(ctx, req.(*GenderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genders.Gender",
	HandlerType: (*GenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenderAll",
			Handler:    _Gender_GenderAll_Handler,
		},
		{
			MethodName: "GetGenderById",
			Handler:    _Gender_GetGenderById_Handler,
		},
		{
			MethodName: "CreateGender",
			Handler:    _Gender_CreateGender_Handler,
		},
		{
			MethodName: "DeleteGender",
			Handler:    _Gender_DeleteGender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/customer.proto",
}
