// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/customer.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenderListResponse struct {
	Genderitemresponse   []*GenderItemResponse `protobuf:"bytes,1,rep,name=genderitemresponse,proto3" json:"genderitemresponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GenderListResponse) Reset()         { *m = GenderListResponse{} }
func (m *GenderListResponse) String() string { return proto.CompactTextString(m) }
func (*GenderListResponse) ProtoMessage()    {}
func (*GenderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{0}
}

func (m *GenderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderListResponse.Unmarshal(m, b)
}
func (m *GenderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderListResponse.Marshal(b, m, deterministic)
}
func (m *GenderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderListResponse.Merge(m, src)
}
func (m *GenderListResponse) XXX_Size() int {
	return xxx_messageInfo_GenderListResponse.Size(m)
}
func (m *GenderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenderListResponse proto.InternalMessageInfo

func (m *GenderListResponse) GetGenderitemresponse() []*GenderItemResponse {
	if m != nil {
		return m.Genderitemresponse
	}
	return nil
}

type GenderItemResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenderItemResponse) Reset()         { *m = GenderItemResponse{} }
func (m *GenderItemResponse) String() string { return proto.CompactTextString(m) }
func (*GenderItemResponse) ProtoMessage()    {}
func (*GenderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{1}
}

func (m *GenderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderItemResponse.Unmarshal(m, b)
}
func (m *GenderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderItemResponse.Marshal(b, m, deterministic)
}
func (m *GenderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderItemResponse.Merge(m, src)
}
func (m *GenderItemResponse) XXX_Size() int {
	return xxx_messageInfo_GenderItemResponse.Size(m)
}
func (m *GenderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenderItemResponse proto.InternalMessageInfo

func (m *GenderItemResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GenderItemResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GenderItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenderItemRequest) Reset()         { *m = GenderItemRequest{} }
func (m *GenderItemRequest) String() string { return proto.CompactTextString(m) }
func (*GenderItemRequest) ProtoMessage()    {}
func (*GenderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{2}
}

func (m *GenderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderItemRequest.Unmarshal(m, b)
}
func (m *GenderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderItemRequest.Marshal(b, m, deterministic)
}
func (m *GenderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderItemRequest.Merge(m, src)
}
func (m *GenderItemRequest) XXX_Size() int {
	return xxx_messageInfo_GenderItemRequest.Size(m)
}
func (m *GenderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenderItemRequest proto.InternalMessageInfo

func (m *GenderItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateGenderItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGenderItemRequest) Reset()         { *m = CreateGenderItemRequest{} }
func (m *CreateGenderItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGenderItemRequest) ProtoMessage()    {}
func (*CreateGenderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{3}
}

func (m *CreateGenderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGenderItemRequest.Unmarshal(m, b)
}
func (m *CreateGenderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGenderItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateGenderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGenderItemRequest.Merge(m, src)
}
func (m *CreateGenderItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGenderItemRequest.Size(m)
}
func (m *CreateGenderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGenderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGenderItemRequest proto.InternalMessageInfo

func (m *CreateGenderItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteGenderItemResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGenderItemResponse) Reset()         { *m = DeleteGenderItemResponse{} }
func (m *DeleteGenderItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGenderItemResponse) ProtoMessage()    {}
func (*DeleteGenderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{4}
}

func (m *DeleteGenderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGenderItemResponse.Unmarshal(m, b)
}
func (m *DeleteGenderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGenderItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGenderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGenderItemResponse.Merge(m, src)
}
func (m *DeleteGenderItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGenderItemResponse.Size(m)
}
func (m *DeleteGenderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGenderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGenderItemResponse proto.InternalMessageInfo

func (m *DeleteGenderItemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CountryListResponse struct {
	Countryitemresponse  []*CountryItemResponse `protobuf:"bytes,1,rep,name=countryitemresponse,proto3" json:"countryitemresponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CountryListResponse) Reset()         { *m = CountryListResponse{} }
func (m *CountryListResponse) String() string { return proto.CompactTextString(m) }
func (*CountryListResponse) ProtoMessage()    {}
func (*CountryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{5}
}

func (m *CountryListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountryListResponse.Unmarshal(m, b)
}
func (m *CountryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountryListResponse.Marshal(b, m, deterministic)
}
func (m *CountryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountryListResponse.Merge(m, src)
}
func (m *CountryListResponse) XXX_Size() int {
	return xxx_messageInfo_CountryListResponse.Size(m)
}
func (m *CountryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountryListResponse proto.InternalMessageInfo

func (m *CountryListResponse) GetCountryitemresponse() []*CountryItemResponse {
	if m != nil {
		return m.Countryitemresponse
	}
	return nil
}

type CountryItemResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Countryid            int32    `protobuf:"varint,2,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountryItemResponse) Reset()         { *m = CountryItemResponse{} }
func (m *CountryItemResponse) String() string { return proto.CompactTextString(m) }
func (*CountryItemResponse) ProtoMessage()    {}
func (*CountryItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{6}
}

func (m *CountryItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountryItemResponse.Unmarshal(m, b)
}
func (m *CountryItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountryItemResponse.Marshal(b, m, deterministic)
}
func (m *CountryItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountryItemResponse.Merge(m, src)
}
func (m *CountryItemResponse) XXX_Size() int {
	return xxx_messageInfo_CountryItemResponse.Size(m)
}
func (m *CountryItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountryItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountryItemResponse proto.InternalMessageInfo

func (m *CountryItemResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CountryItemResponse) GetCountryid() int32 {
	if m != nil {
		return m.Countryid
	}
	return 0
}

func (m *CountryItemResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CountryItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountryItemRequest) Reset()         { *m = CountryItemRequest{} }
func (m *CountryItemRequest) String() string { return proto.CompactTextString(m) }
func (*CountryItemRequest) ProtoMessage()    {}
func (*CountryItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{7}
}

func (m *CountryItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountryItemRequest.Unmarshal(m, b)
}
func (m *CountryItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountryItemRequest.Marshal(b, m, deterministic)
}
func (m *CountryItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountryItemRequest.Merge(m, src)
}
func (m *CountryItemRequest) XXX_Size() int {
	return xxx_messageInfo_CountryItemRequest.Size(m)
}
func (m *CountryItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountryItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountryItemRequest proto.InternalMessageInfo

func (m *CountryItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateCountryItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Countryid            int32    `protobuf:"varint,2,opt,name=countryid,proto3" json:"countryid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCountryItemRequest) Reset()         { *m = CreateCountryItemRequest{} }
func (m *CreateCountryItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCountryItemRequest) ProtoMessage()    {}
func (*CreateCountryItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{8}
}

func (m *CreateCountryItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCountryItemRequest.Unmarshal(m, b)
}
func (m *CreateCountryItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCountryItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateCountryItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCountryItemRequest.Merge(m, src)
}
func (m *CreateCountryItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCountryItemRequest.Size(m)
}
func (m *CreateCountryItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCountryItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCountryItemRequest proto.InternalMessageInfo

func (m *CreateCountryItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCountryItemRequest) GetCountryid() int32 {
	if m != nil {
		return m.Countryid
	}
	return 0
}

type DeleteCountryItemResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCountryItemResponse) Reset()         { *m = DeleteCountryItemResponse{} }
func (m *DeleteCountryItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCountryItemResponse) ProtoMessage()    {}
func (*DeleteCountryItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{9}
}

func (m *DeleteCountryItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCountryItemResponse.Unmarshal(m, b)
}
func (m *DeleteCountryItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCountryItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCountryItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCountryItemResponse.Merge(m, src)
}
func (m *DeleteCountryItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCountryItemResponse.Size(m)
}
func (m *DeleteCountryItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCountryItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCountryItemResponse proto.InternalMessageInfo

func (m *DeleteCountryItemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProvinceListResponse struct {
	Provinceitemresponse []*ProvinceItemResponse `protobuf:"bytes,1,rep,name=provinceitemresponse,proto3" json:"provinceitemresponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProvinceListResponse) Reset()         { *m = ProvinceListResponse{} }
func (m *ProvinceListResponse) String() string { return proto.CompactTextString(m) }
func (*ProvinceListResponse) ProtoMessage()    {}
func (*ProvinceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{10}
}

func (m *ProvinceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvinceListResponse.Unmarshal(m, b)
}
func (m *ProvinceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvinceListResponse.Marshal(b, m, deterministic)
}
func (m *ProvinceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvinceListResponse.Merge(m, src)
}
func (m *ProvinceListResponse) XXX_Size() int {
	return xxx_messageInfo_ProvinceListResponse.Size(m)
}
func (m *ProvinceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvinceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvinceListResponse proto.InternalMessageInfo

func (m *ProvinceListResponse) GetProvinceitemresponse() []*ProvinceItemResponse {
	if m != nil {
		return m.Provinceitemresponse
	}
	return nil
}

type ProvinceItemResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProvinceId           int32    `protobuf:"varint,3,opt,name=provinceId,proto3" json:"provinceId,omitempty"`
	CountryId            int32    `protobuf:"varint,4,opt,name=countryId,proto3" json:"countryId,omitempty"`
	CountryName          string   `protobuf:"bytes,5,opt,name=countryName,proto3" json:"countryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvinceItemResponse) Reset()         { *m = ProvinceItemResponse{} }
func (m *ProvinceItemResponse) String() string { return proto.CompactTextString(m) }
func (*ProvinceItemResponse) ProtoMessage()    {}
func (*ProvinceItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{11}
}

func (m *ProvinceItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvinceItemResponse.Unmarshal(m, b)
}
func (m *ProvinceItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvinceItemResponse.Marshal(b, m, deterministic)
}
func (m *ProvinceItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvinceItemResponse.Merge(m, src)
}
func (m *ProvinceItemResponse) XXX_Size() int {
	return xxx_messageInfo_ProvinceItemResponse.Size(m)
}
func (m *ProvinceItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvinceItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvinceItemResponse proto.InternalMessageInfo

func (m *ProvinceItemResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProvinceItemResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProvinceItemResponse) GetProvinceId() int32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *ProvinceItemResponse) GetCountryId() int32 {
	if m != nil {
		return m.CountryId
	}
	return 0
}

func (m *ProvinceItemResponse) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

type ProvinceItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvinceItemRequest) Reset()         { *m = ProvinceItemRequest{} }
func (m *ProvinceItemRequest) String() string { return proto.CompactTextString(m) }
func (*ProvinceItemRequest) ProtoMessage()    {}
func (*ProvinceItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{12}
}

func (m *ProvinceItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvinceItemRequest.Unmarshal(m, b)
}
func (m *ProvinceItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvinceItemRequest.Marshal(b, m, deterministic)
}
func (m *ProvinceItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvinceItemRequest.Merge(m, src)
}
func (m *ProvinceItemRequest) XXX_Size() int {
	return xxx_messageInfo_ProvinceItemRequest.Size(m)
}
func (m *ProvinceItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvinceItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvinceItemRequest proto.InternalMessageInfo

func (m *ProvinceItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateProvinceItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Countryid            int32    `protobuf:"varint,2,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Provinceid           int32    `protobuf:"varint,3,opt,name=provinceid,proto3" json:"provinceid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProvinceItemRequest) Reset()         { *m = CreateProvinceItemRequest{} }
func (m *CreateProvinceItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProvinceItemRequest) ProtoMessage()    {}
func (*CreateProvinceItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{13}
}

func (m *CreateProvinceItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProvinceItemRequest.Unmarshal(m, b)
}
func (m *CreateProvinceItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProvinceItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateProvinceItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProvinceItemRequest.Merge(m, src)
}
func (m *CreateProvinceItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProvinceItemRequest.Size(m)
}
func (m *CreateProvinceItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProvinceItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProvinceItemRequest proto.InternalMessageInfo

func (m *CreateProvinceItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProvinceItemRequest) GetCountryid() int32 {
	if m != nil {
		return m.Countryid
	}
	return 0
}

func (m *CreateProvinceItemRequest) GetProvinceid() int32 {
	if m != nil {
		return m.Provinceid
	}
	return 0
}

type DeleteProvinceItemResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProvinceItemResponse) Reset()         { *m = DeleteProvinceItemResponse{} }
func (m *DeleteProvinceItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProvinceItemResponse) ProtoMessage()    {}
func (*DeleteProvinceItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d164c08f51b4bb12, []int{14}
}

func (m *DeleteProvinceItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProvinceItemResponse.Unmarshal(m, b)
}
func (m *DeleteProvinceItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProvinceItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProvinceItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProvinceItemResponse.Merge(m, src)
}
func (m *DeleteProvinceItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProvinceItemResponse.Size(m)
}
func (m *DeleteProvinceItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProvinceItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProvinceItemResponse proto.InternalMessageInfo

func (m *DeleteProvinceItemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GenderListResponse)(nil), "services.GenderListResponse")
	proto.RegisterType((*GenderItemResponse)(nil), "services.GenderItemResponse")
	proto.RegisterType((*GenderItemRequest)(nil), "services.GenderItemRequest")
	proto.RegisterType((*CreateGenderItemRequest)(nil), "services.CreateGenderItemRequest")
	proto.RegisterType((*DeleteGenderItemResponse)(nil), "services.DeleteGenderItemResponse")
	proto.RegisterType((*CountryListResponse)(nil), "services.CountryListResponse")
	proto.RegisterType((*CountryItemResponse)(nil), "services.CountryItemResponse")
	proto.RegisterType((*CountryItemRequest)(nil), "services.CountryItemRequest")
	proto.RegisterType((*CreateCountryItemRequest)(nil), "services.CreateCountryItemRequest")
	proto.RegisterType((*DeleteCountryItemResponse)(nil), "services.DeleteCountryItemResponse")
	proto.RegisterType((*ProvinceListResponse)(nil), "services.ProvinceListResponse")
	proto.RegisterType((*ProvinceItemResponse)(nil), "services.ProvinceItemResponse")
	proto.RegisterType((*ProvinceItemRequest)(nil), "services.ProvinceItemRequest")
	proto.RegisterType((*CreateProvinceItemRequest)(nil), "services.CreateProvinceItemRequest")
	proto.RegisterType((*DeleteProvinceItemResponse)(nil), "services.DeleteProvinceItemResponse")
}

func init() { proto.RegisterFile("proto/customer.proto", fileDescriptor_d164c08f51b4bb12) }

var fileDescriptor_d164c08f51b4bb12 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x6f, 0x6f, 0xda, 0x30,
	0x10, 0xc6, 0x49, 0x5b, 0xd6, 0x71, 0xac, 0x54, 0x33, 0xd5, 0x96, 0x52, 0x5a, 0x31, 0xd3, 0x49,
	0xbc, 0x59, 0x90, 0xba, 0x3f, 0xda, 0xdb, 0x8d, 0x55, 0x08, 0x09, 0xad, 0x5b, 0x36, 0xa9, 0xaf,
	0x81, 0x5c, 0x51, 0x26, 0x92, 0xb0, 0xc4, 0x54, 0xea, 0x57, 0xd9, 0x77, 0xdb, 0x77, 0x99, 0xb0,
	0xe3, 0xc6, 0x0e, 0x4e, 0x58, 0xfb, 0x2e, 0x39, 0xdf, 0x3d, 0x3e, 0xff, 0xce, 0x7e, 0xe0, 0x68,
	0x19, 0x47, 0x2c, 0xea, 0xcf, 0x56, 0x09, 0x8b, 0x02, 0x8c, 0x1d, 0xfe, 0x4b, 0x9e, 0x26, 0x18,
	0xdf, 0xfa, 0x33, 0x4c, 0x5a, 0x27, 0xf3, 0x28, 0x9a, 0x2f, 0xb0, 0xcf, 0xe3, 0xd3, 0xd5, 0x4d,
	0x1f, 0x83, 0x25, 0xbb, 0x13, 0x69, 0x74, 0x0a, 0x64, 0x88, 0xa1, 0x87, 0xf1, 0xd8, 0x4f, 0x98,
	0x8b, 0xc9, 0x32, 0x0a, 0x13, 0x24, 0x63, 0x20, 0x73, 0x1e, 0xf5, 0x19, 0x06, 0x71, 0x1a, 0xb5,
	0xad, 0xce, 0x6e, 0xaf, 0x7e, 0xd1, 0x76, 0xa4, 0xb2, 0x23, 0x2a, 0x47, 0x0c, 0x03, 0x59, 0xe9,
	0x1a, 0xea, 0xe8, 0x47, 0xb9, 0x87, 0x9a, 0x49, 0x1a, 0xb0, 0xe3, 0x7b, 0xb6, 0xd5, 0xb1, 0x7a,
	0x55, 0x77, 0xc7, 0xf7, 0x08, 0x81, 0xbd, 0x70, 0x12, 0xa0, 0xbd, 0xd3, 0xb1, 0x7a, 0x35, 0x97,
	0x7f, 0xd3, 0x2e, 0x3c, 0x57, 0x2b, 0x7f, 0xaf, 0x30, 0x61, 0xf9, 0x42, 0xfa, 0x06, 0x5e, 0x0e,
	0x62, 0x9c, 0x30, 0xdc, 0x4c, 0x95, 0x9a, 0x96, 0xa2, 0xf9, 0x0e, 0xec, 0x2f, 0xb8, 0x40, 0x3d,
	0x3d, 0xed, 0xc9, 0x86, 0xfd, 0x00, 0x93, 0x64, 0x32, 0x97, 0x25, 0xf2, 0x97, 0xde, 0x40, 0x73,
	0x10, 0xad, 0x42, 0x16, 0xdf, 0x69, 0xa0, 0xae, 0xa0, 0x39, 0x13, 0x61, 0x03, 0xa9, 0xd3, 0x8c,
	0x54, 0x5a, 0xab, 0xa1, 0x32, 0x55, 0xd2, 0xeb, 0xfb, 0x7d, 0x4a, 0x61, 0xb5, 0xa1, 0x26, 0xab,
	0x3d, 0x4e, 0xac, 0xea, 0x66, 0x81, 0xfb, 0x63, 0xef, 0x2a, 0xc7, 0x3e, 0x07, 0xa2, 0x09, 0x9b,
	0x59, 0x8e, 0xc1, 0x16, 0x2c, 0x0d, 0xb9, 0x06, 0x98, 0xe5, 0x7d, 0xd0, 0xf7, 0x70, 0x2c, 0x50,
	0x9b, 0x8e, 0x54, 0xcc, 0xfa, 0x17, 0x1c, 0x7d, 0x8b, 0xa3, 0x5b, 0x3f, 0x9c, 0xa1, 0x06, 0xdb,
	0xe5, 0x57, 0x9d, 0xc7, 0x0d, 0xb4, 0xcf, 0x32, 0xda, 0xb2, 0x5a, 0xc3, 0x6d, 0xac, 0xa5, 0x7f,
	0xac, 0x6c, 0xb3, 0x87, 0x5e, 0x4f, 0x72, 0x06, 0x20, 0x45, 0x47, 0x1e, 0xa7, 0x5d, 0x75, 0x95,
	0x88, 0x42, 0x67, 0xe4, 0xd9, 0x7b, 0x1a, 0x9d, 0x91, 0x47, 0x3a, 0x50, 0x4f, 0x7f, 0xbe, 0xae,
	0x85, 0xab, 0x5c, 0x58, 0x0d, 0xd1, 0xd7, 0xd0, 0xd4, 0x7b, 0x33, 0x0f, 0x2d, 0x80, 0x63, 0x31,
	0x34, 0x53, 0xf2, 0x83, 0xa7, 0xa6, 0x9e, 0xca, 0xdf, 0x38, 0x95, 0xef, 0xd1, 0x0f, 0xd0, 0x12,
	0x53, 0x35, 0x72, 0x2b, 0x1c, 0xeb, 0xc5, 0xdf, 0x7d, 0x38, 0x1c, 0xa4, 0x26, 0xf5, 0x43, 0x8c,
	0x8a, 0x0c, 0xa0, 0x26, 0x9e, 0xe1, 0xa7, 0xc5, 0x82, 0xbc, 0x70, 0x84, 0x53, 0x39, 0xd2, 0xa9,
	0x9c, 0xcb, 0xb5, 0x53, 0xb5, 0x36, 0x1c, 0x47, 0xbd, 0x15, 0xb4, 0x42, 0xc6, 0x70, 0x30, 0x44,
	0x26, 0x96, 0x3e, 0xaf, 0xc9, 0x9e, 0x98, 0x2d, 0x8a, 0x03, 0x69, 0x95, 0xfa, 0x17, 0xad, 0x90,
	0xef, 0xf0, 0x4c, 0xb5, 0x13, 0xf2, 0x4a, 0x79, 0xc5, 0x66, 0x9b, 0xf9, 0x1f, 0x49, 0xd5, 0x72,
	0xca, 0xfb, 0xa3, 0xd9, 0x62, 0x91, 0x4f, 0xd1, 0x0a, 0xb9, 0x04, 0x48, 0x1f, 0x55, 0x19, 0xb9,
	0x4d, 0x07, 0xca, 0xa1, 0xbb, 0x82, 0xc6, 0x10, 0x59, 0xba, 0xc6, 0xd9, 0xb5, 0x0b, 0x4c, 0x4b,
	0x34, 0x57, 0x6e, 0x69, 0xb4, 0x42, 0x7e, 0xc2, 0x81, 0x66, 0x20, 0x84, 0xe6, 0xf1, 0x3d, 0x52,
	0x55, 0x33, 0x92, 0x2d, 0x5d, 0x76, 0xf3, 0x08, 0xcd, 0xaa, 0x43, 0xa8, 0xcb, 0x2b, 0x5c, 0x06,
	0xd1, 0x60, 0x2c, 0x39, 0x8a, 0x2e, 0x1c, 0x0e, 0x91, 0xc9, 0x45, 0x8e, 0xf1, 0xb4, 0xc8, 0x8d,
	0x44, 0x87, 0x5b, 0xcc, 0x8a, 0x56, 0xc8, 0x35, 0x34, 0xf4, 0x47, 0x4d, 0xba, 0x79, 0x92, 0x8f,
	0x16, 0xd6, 0x9f, 0xef, 0xb6, 0x5e, 0xcf, 0xf3, 0x34, 0xcd, 0xc2, 0xd3, 0x27, 0x9c, 0xdb, 0xdb,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xcf, 0x0e, 0x89, 0x90, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	GenderAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenderListResponse, error)
	GetGenderById(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error)
	CreateGender(ctx context.Context, in *CreateGenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error)
	DeleteGender(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*DeleteGenderItemResponse, error)
	CountryAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountryListResponse, error)
	GetCountryById(ctx context.Context, in *CountryItemRequest, opts ...grpc.CallOption) (*CountryItemResponse, error)
	CreateCountry(ctx context.Context, in *CreateCountryItemRequest, opts ...grpc.CallOption) (*CountryItemResponse, error)
	DeleteCountry(ctx context.Context, in *CountryItemRequest, opts ...grpc.CallOption) (*DeleteCountryItemResponse, error)
	ProvinceAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProvinceListResponse, error)
	GetProvinceById(ctx context.Context, in *ProvinceItemRequest, opts ...grpc.CallOption) (*ProvinceItemResponse, error)
	CreateProvince(ctx context.Context, in *CreateProvinceItemRequest, opts ...grpc.CallOption) (*ProvinceItemResponse, error)
	DeleteProvince(ctx context.Context, in *ProvinceItemRequest, opts ...grpc.CallOption) (*DeleteProvinceItemResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) GenderAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenderListResponse, error) {
	out := new(GenderListResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/GenderAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetGenderById(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error) {
	out := new(GenderItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/GetGenderById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CreateGender(ctx context.Context, in *CreateGenderItemRequest, opts ...grpc.CallOption) (*GenderItemResponse, error) {
	out := new(GenderItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/CreateGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) DeleteGender(ctx context.Context, in *GenderItemRequest, opts ...grpc.CallOption) (*DeleteGenderItemResponse, error) {
	out := new(DeleteGenderItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/DeleteGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CountryAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountryListResponse, error) {
	out := new(CountryListResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/CountryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCountryById(ctx context.Context, in *CountryItemRequest, opts ...grpc.CallOption) (*CountryItemResponse, error) {
	out := new(CountryItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/GetCountryById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CreateCountry(ctx context.Context, in *CreateCountryItemRequest, opts ...grpc.CallOption) (*CountryItemResponse, error) {
	out := new(CountryItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/CreateCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) DeleteCountry(ctx context.Context, in *CountryItemRequest, opts ...grpc.CallOption) (*DeleteCountryItemResponse, error) {
	out := new(DeleteCountryItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/DeleteCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) ProvinceAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProvinceListResponse, error) {
	out := new(ProvinceListResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/ProvinceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetProvinceById(ctx context.Context, in *ProvinceItemRequest, opts ...grpc.CallOption) (*ProvinceItemResponse, error) {
	out := new(ProvinceItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/GetProvinceById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CreateProvince(ctx context.Context, in *CreateProvinceItemRequest, opts ...grpc.CallOption) (*ProvinceItemResponse, error) {
	out := new(ProvinceItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/CreateProvince", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) DeleteProvince(ctx context.Context, in *ProvinceItemRequest, opts ...grpc.CallOption) (*DeleteProvinceItemResponse, error) {
	out := new(DeleteProvinceItemResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/DeleteProvince", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	GenderAll(context.Context, *empty.Empty) (*GenderListResponse, error)
	GetGenderById(context.Context, *GenderItemRequest) (*GenderItemResponse, error)
	CreateGender(context.Context, *CreateGenderItemRequest) (*GenderItemResponse, error)
	DeleteGender(context.Context, *GenderItemRequest) (*DeleteGenderItemResponse, error)
	CountryAll(context.Context, *empty.Empty) (*CountryListResponse, error)
	GetCountryById(context.Context, *CountryItemRequest) (*CountryItemResponse, error)
	CreateCountry(context.Context, *CreateCountryItemRequest) (*CountryItemResponse, error)
	DeleteCountry(context.Context, *CountryItemRequest) (*DeleteCountryItemResponse, error)
	ProvinceAll(context.Context, *empty.Empty) (*ProvinceListResponse, error)
	GetProvinceById(context.Context, *ProvinceItemRequest) (*ProvinceItemResponse, error)
	CreateProvince(context.Context, *CreateProvinceItemRequest) (*ProvinceItemResponse, error)
	DeleteProvince(context.Context, *ProvinceItemRequest) (*DeleteProvinceItemResponse, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) GenderAll(ctx context.Context, req *empty.Empty) (*GenderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenderAll not implemented")
}
func (*UnimplementedCustomerServiceServer) GetGenderById(ctx context.Context, req *GenderItemRequest) (*GenderItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenderById not implemented")
}
func (*UnimplementedCustomerServiceServer) CreateGender(ctx context.Context, req *CreateGenderItemRequest) (*GenderItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGender not implemented")
}
func (*UnimplementedCustomerServiceServer) DeleteGender(ctx context.Context, req *GenderItemRequest) (*DeleteGenderItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGender not implemented")
}
func (*UnimplementedCustomerServiceServer) CountryAll(ctx context.Context, req *empty.Empty) (*CountryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountryAll not implemented")
}
func (*UnimplementedCustomerServiceServer) GetCountryById(ctx context.Context, req *CountryItemRequest) (*CountryItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountryById not implemented")
}
func (*UnimplementedCustomerServiceServer) CreateCountry(ctx context.Context, req *CreateCountryItemRequest) (*CountryItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCountry not implemented")
}
func (*UnimplementedCustomerServiceServer) DeleteCountry(ctx context.Context, req *CountryItemRequest) (*DeleteCountryItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCountry not implemented")
}
func (*UnimplementedCustomerServiceServer) ProvinceAll(ctx context.Context, req *empty.Empty) (*ProvinceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvinceAll not implemented")
}
func (*UnimplementedCustomerServiceServer) GetProvinceById(ctx context.Context, req *ProvinceItemRequest) (*ProvinceItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvinceById not implemented")
}
func (*UnimplementedCustomerServiceServer) CreateProvince(ctx context.Context, req *CreateProvinceItemRequest) (*ProvinceItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProvince not implemented")
}
func (*UnimplementedCustomerServiceServer) DeleteProvince(ctx context.Context, req *ProvinceItemRequest) (*DeleteProvinceItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProvince not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_GenderAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GenderAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/GenderAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GenderAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetGenderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetGenderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/GetGenderById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetGenderById(ctx, req.(*GenderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CreateGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGenderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/CreateGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateGender(ctx, req.(*CreateGenderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_DeleteGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).DeleteGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/DeleteGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).DeleteGender(ctx, req.(*GenderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CountryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CountryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/CountryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CountryAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCountryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCountryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/GetCountryById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCountryById(ctx, req.(*CountryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CreateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCountryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/CreateCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCountry(ctx, req.(*CreateCountryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_DeleteCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).DeleteCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/DeleteCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).DeleteCountry(ctx, req.(*CountryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_ProvinceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).ProvinceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/ProvinceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).ProvinceAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetProvinceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvinceItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetProvinceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/GetProvinceById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetProvinceById(ctx, req.(*ProvinceItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CreateProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProvinceItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/CreateProvince",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateProvince(ctx, req.(*CreateProvinceItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_DeleteProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvinceItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).DeleteProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/DeleteProvince",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).DeleteProvince(ctx, req.(*ProvinceItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenderAll",
			Handler:    _CustomerService_GenderAll_Handler,
		},
		{
			MethodName: "GetGenderById",
			Handler:    _CustomerService_GetGenderById_Handler,
		},
		{
			MethodName: "CreateGender",
			Handler:    _CustomerService_CreateGender_Handler,
		},
		{
			MethodName: "DeleteGender",
			Handler:    _CustomerService_DeleteGender_Handler,
		},
		{
			MethodName: "CountryAll",
			Handler:    _CustomerService_CountryAll_Handler,
		},
		{
			MethodName: "GetCountryById",
			Handler:    _CustomerService_GetCountryById_Handler,
		},
		{
			MethodName: "CreateCountry",
			Handler:    _CustomerService_CreateCountry_Handler,
		},
		{
			MethodName: "DeleteCountry",
			Handler:    _CustomerService_DeleteCountry_Handler,
		},
		{
			MethodName: "ProvinceAll",
			Handler:    _CustomerService_ProvinceAll_Handler,
		},
		{
			MethodName: "GetProvinceById",
			Handler:    _CustomerService_GetProvinceById_Handler,
		},
		{
			MethodName: "CreateProvince",
			Handler:    _CustomerService_CreateProvince_Handler,
		},
		{
			MethodName: "DeleteProvince",
			Handler:    _CustomerService_DeleteProvince_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/customer.proto",
}
